swagger: '2.0'
info:
  version: '1.0.0'
  title: Fulcio
schemes: [http, https]
host: fulcio.sigstore.dev
basePath: /api/v1
securityDefinitions:
  Bearer:
    type: apiKey
    in: header
    name: Authorization
paths:
  /signingCert:
    post:
      security:
        - Bearer: []
      description: 'create a cert, return content with a location header (with URL to CTL entry)'
      operationId: signingCert
      consumes:
        - application/json
      produces:
        - application/pem-certificate-chain
      parameters:
        - name: 'CertificateRequest'
          in: 'body'
          required: true
          description: 'Request for signing certificate'
          schema:
            $ref: '#/definitions/CertificateRequest'
      responses:
        201:
          description: Generated Certificate Chain
          schema:
            type: string
        400:
          $ref: '#/responses/BadContent'
        401:
          $ref: '#/responses/Unauthorized'
        default:
          $ref: '#/responses/InternalServerError'

definitions:
  CertificateRequest:
    type: object
    properties:
      publicKey:
        type: string
        format: byte
      signedEmailAddress:
        type: string
        format: byte
    required:
      - publicKey
      - signedEmailAddress
  Error:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string

responses:
  BadContent:
    description: The content supplied to the server was invalid
    schema:
      $ref: "#/definitions/Error"
    headers:
      Content-Type:
        type: string
  Unauthorized:
    description: The request could not be authorized
    schema:
      $ref: "#/definitions/Error"
    headers:
      Content-Type:
        type: string
      WWW-Authenticate:
        type: string
        description: Information about required authentication to access server
  InternalServerError:
    description: There was an internal error in the server while processing the request
    schema:
      $ref: "#/definitions/Error"
    headers:
      Content-Type:
        type: string
