#
# Copyright 2021 The Sigstore Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fulcio-dev
  name: fulcio-server
  labels:
    app: fulcio-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fulcio-server
  template:
    metadata:
      labels:
        app: fulcio-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "2112"
    spec:
      containers:
      - name: fulcio-server
        image: ko://github.com/sigstore/fulcio
        ports:
        - containerPort: 5555
        - containerPort: 2112 # metrics
        args: [
          "serve",
          "--host=0.0.0.0", "--port=5555", "--ca=fulcioca", "--hsm-caroot-id=1", "--ct-log-url=http://ct-log/test",
        ]
        env:
        - name: CA_PARENT
          valueFrom:
            configMapKeyRef:
              name: private-ca
              key: connection
        volumeMounts:
        - name: fulcio-config
          mountPath: /etc/fulcio-config
        resources:
          requests:
            memory: "1G"
            cpu: ".5"
      volumes:
      - name: fulcio-config
        configMap:
          name: fulcio-config

---
apiVersion: v1
kind: Service
metadata:
  namespace: fulcio-dev
  name: fulcio-server
spec:
  selector:
    app: fulcio-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5555
