apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fulcio-dev
  name: fulcio-server
  labels:
    app: fulcio-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fulcio-server
  template:
    metadata:
      labels:
        app: fulcio-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "2112"
    spec:
      containers:
      - name: fulcio-server
        image: ko://github.com/sigstore/fulcio/cmd/server
        ports:
        - containerPort: 5555
        - containerPort: 2112 # metrics
        args: [
          "serve",
          "--host=0.0.0.0", "--port=5555", "--gcp_private_ca_parent=$(CA_PARENT)", "--ct-log-url=http://ct-log/test",
        ]
        env:
        - name: CA_PARENT
          valueFrom:
            configMapKeyRef:
              name: private-ca
              key: connection
        resources:
          requests:
            memory: "1G"
            cpu: ".5"
---
apiVersion: v1
kind: Service
metadata:
  namespace: fulcio-dev
  name: fulcio-server
spec:
  selector:
    app: fulcio-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5555
---
